// Service to interface with GitHub Actions API and simulate pipelines

// Helper to extract owner and repo from a GitHub URL or string
export function parseGitHubRepo(repoString) {
  if (!repoString) return { owner: '', repo: '' };
  
  // Clean URL if full path provided
  const cleanStr = repoString.replace(/https?:\/\/github\.com\//, '');
  const parts = cleanStr.split('/');
  
  return {
    owner: parts[0] || '',
    repo: parts[1] || ''
  };
}

// 1. Trigger GitHub Repository Dispatch
export async function triggerGitHubDispatch({ owner, repo, token, eventType = 'process-reel', reelUrl }) {
  if (!owner || !repo || !token) {
    throw new Error('GitHub configuration missing (Owner, Repo, and Token are required).');
  }

  const cleanOwner = owner.trim();
  const cleanRepo = repo.trim();
  const cleanToken = token.trim();

  const url = `https://api.github.com/repos/${cleanOwner}/${cleanRepo}/dispatches`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Accept': 'application/vnd.github+json',
      'Authorization': `Bearer ${cleanToken}`,
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      event_type: eventType,
      client_payload: {
        url: reelUrl
      }
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`GitHub API Error (${response.status}): ${errorText || response.statusText}`);
  }

  return true;
}

// 2. Fetch Workflow Runs to check progress
export async function fetchWorkflowRuns({ owner, repo, token }) {
  if (!owner || !repo || !token) return [];

  const url = `https://api.github.com/repos/${owner.trim()}/${repo.trim()}/actions/runs?event=repository_dispatch&per_page=5`;

  try {
    const response = await fetch(url, {
      headers: {
        'Accept': 'application/vnd.github+json',
        'Authorization': `Bearer ${token.trim()}`,
        'X-GitHub-Api-Version': '2022-11-28'
      }
    });

    if (!response.ok) return [];

    const data = await response.json();
    return data.workflow_runs || [];
  } catch (error) {
    console.error('Error fetching workflow runs:', error);
    return [];
  }
}

// 3. High-Fidelity Simulation Engine
// Generates terminal logs and returns a mock processed Reel based on the URL input
export function startPipelineSimulation(reelUrl, onLog, onComplete) {
  // Determine a mock theme based on keywords in URL
  const lowerUrl = reelUrl.toLowerCase();
  let category = 'Lifestyle';
  let title = 'Smart Ingested Instagram Reel';
  let summary = 'A curated digital insight summarizing this Instagram Reel clip.';
  let tags = ['General', 'Social'];
  let notes = 'Auto-generated notes from ingestion.';
  let transcript = 'This is a simulated transcript generated by the Whisper speech recognition model.';

  if (lowerUrl.includes('food') || lowerUrl.includes('cook') || lowerUrl.includes('recipe') || lowerUrl.includes('eat') || lowerUrl.includes('chef')) {
    category = 'Food';
    title = 'Savory Garlic Herb Butter Steak Skillet';
    summary = 'A professional kitchen walkthrough showing how to pan-sear a ribeye steak to a perfect medium-rare, basting with garlic, fresh rosemary, and artisanal butter.';
    tags = ['cooking', 'steak', 'recipe', 'culinary', 'dinner'];
    notes = 'Try adding sliced mushrooms in the pan during the final 3 minutes of basting. Serve alongside roasted asparagus.';
    transcript = '[Upbeat Acoustic Guitar] Hey guys, today we are searing a gorgeous dry-aged ribeye! Get your cast-iron skillet screaming hot, add avocado oil, and lay that steak down. Sear for 3 minutes until a deep golden crust forms. Flip it, then throw in a half-bar of unsalted butter, crushed garlic cloves, and sprigs of fresh rosemary. Tilt the pan and continuously spoon that melted butter right over the steak. Rest it for 5 minutes, slice it up, and look at that perfect pink center! Pure perfection.';
  } else if (lowerUrl.includes('travel') || lowerUrl.includes('trip') || lowerUrl.includes('vacation') || lowerUrl.includes('beach') || lowerUrl.includes('explore')) {
    category = 'Travel';
    title = '5 Budget Maldives Water Villas You Wont Believe Exist';
    summary = 'A travel breakdown revealing budget-friendly water villas in the Maldives that cost under $180 a night, including transfers.';
    tags = ['maldives', 'budgettravel', 'watervillas', 'wanderlust', 'islands'];
    notes = 'Book between May and October (rainy season but lower prices) for the absolute lowest rates. Standard speedboat transfers are much cheaper than seaplane transfers.';
    transcript = '[Calm Island Beats] Do you think the Maldives is only for millionaires? Think again! Here are three water villas under one hundred and eighty dollars a night. First is Cinnamon Dhonveli, featuring incredible sunset ocean views. Second is Embudu Village, offering a world-class house reef right outside your bedroom door. And third, Safari Island Resort. Save this reel, share it with your travel squad, and start packing!';
  } else if (lowerUrl.includes('tech') || lowerUrl.includes('code') || lowerUrl.includes('ai') || lowerUrl.includes('dev') || lowerUrl.includes('hack') || lowerUrl.includes('software')) {
    category = 'Tech';
    title = 'The Ultimate Developer Setup Trick to Double Coding Speed';
    summary = 'A step-by-step developer tutorial showcasing productivity workflows, terminal keybind hacks, and AI autocomplete settings that save hours of active dev time.';
    tags = ['developer', 'productivity', 'vscode', 'ai', 'terminal', 'coding'];
    notes = 'Requires installing modern terminal multiplexers and configuring custom shell scripts. Keep keyboard layouts standard for muscle memory.',
    transcript = '[Dynamic Techno Beat] If you are still using your mouse to navigate your code editor, stop! You are losing hours every single week. First, download the Tmux multiplexer to run parallel shell panels. Next, configure custom keybindings in your VSCode settings.json to jump lines instantly. Finally, connect your shell completion to an ultra-fast local LLM server. You will write code twice as fast. Comment "CONFIG" below for my dotfiles!';
  } else if (lowerUrl.includes('funny') || lowerUrl.includes('laugh') || lowerUrl.includes('comedy') || lowerUrl.includes('meme') || lowerUrl.includes('joke')) {
    category = 'Comedy';
    title = 'When the Senior Dev Reviews Your Junior Code';
    summary = 'A hilarious comedy skit contrasting a optimistic junior developer presenting their code with the experienced, silent panic of the senior engineer.';
    tags = ['funny', 'developerhumor', 'juniorcode', 'codereview', 'engineering'];
    notes = 'Highly shareable content, perfect for Slack channels.',
    transcript = '[Fun Clarinet Music] *Junior Dev:* So yeah, I finished the feature! I didn\'t write tests, but it compiles. It only took me 3 days and 4000 lines of code. *Senior Dev stares blankly at a screen of nested loops* *Senior Dev:* ...Is this... a recursive call that loops indefinitely? *Junior Dev:* Well, it ensures the app stays awake! *Senior Dev starts quietly sobbing into his coffee mug* [Laugh Track]';
  } else if (lowerUrl.includes('music') || lowerUrl.includes('song') || lowerUrl.includes('dance') || lowerUrl.includes('beat') || lowerUrl.includes('cover')) {
    category = 'Music';
    title = 'Acoustic Guitar Looper Jam - Midnight Vibes';
    summary = 'A mesmerizing live audio layering performance using an acoustic guitar, a delay pedal, and a multi-track loop station to build a ambient night rhythm.';
    tags = ['acoustic', 'guitar', 'loopstation', 'indie', 'midnight', 'instrumental'];
    notes = 'Beautiful ambient tone. Ideal study or relaxing background track.',
    transcript = '[Live Guitar Audio looping in background] Hey friends, just putting together a quick loop tonight. Started with a percussive slap on the body, layered in a basic root chord progression in E minor, and now adding some ambient delay swells over the top. Let\'s improvise a small melody... [Aesthetic guitar solo plays and fades]';
  }

  const logs = [
    { text: '⚡ Initializing GitHub Actions runner environment...', type: 'info', delay: 200 },
    { text: '✔ Runner online. OS: Ubuntu-22.04 LTS. Arch: x86_64.', type: 'success', delay: 600 },
    { text: '⚙ Fetching workflow dispatch action parameters...', type: 'info', delay: 1000 },
    { text: `🔗 Shared Reel URL received: ${reelUrl}`, type: 'success', delay: 1400 },
    { text: '📥 [yt-dlp] Downloading video streams from Instagram servers...', type: 'info', delay: 1800 },
    { text: '📥 [yt-dlp] Video stream downloaded: 1080p MP4 H264 (8.2 MB)', type: 'success', delay: 2800 },
    { text: '📥 [yt-dlp] Audio stream downloaded: AAC Stereo (780 KB)', type: 'success', delay: 3200 },
    { text: '🎬 [VideoPrism] Initializing Google VideoPrism frame analyzer...', type: 'info', delay: 3700 },
    { text: '🎬 [VideoPrism] Extracted keyframes at 1fps. Generating frame embeddings...', type: 'info', delay: 4200 },
    { text: `🎬 [VideoPrism] Frame classification complete. Dominant Topic: ${category}`, type: 'success', delay: 5000 },
    { text: '🎙 [Whisper] Loading open-source Whisper speech-to-text engine...', type: 'info', delay: 5500 },
    { text: '🎙 [Whisper] Transcribing audio stream waveforms into English text...', type: 'info', delay: 6000 },
    { text: '🎙 [Whisper] Audio transcription complete. Confidence score: 98.4%', type: 'success', delay: 7200 },
    { text: '🧠 [Groq LLaMA-3] Synthesizing transcript & caption metadata...', type: 'info', delay: 7800 },
    { text: '🧠 [Groq LLaMA-3] Creating structured summary, title, and categorization...', type: 'info', delay: 8400 },
    { text: '💾 [Database] Establishing sync connection to central Supabase DB...', type: 'info', delay: 9200 },
    { text: '💾 [Database] Successfully registered metadata in central schema.', type: 'success', delay: 9800 },
    { text: '🎉 [Pipeline] Ingestion workflow successfully completed! Run ID: #run_' + Math.floor(Math.random() * 900000 + 100000), type: 'success', delay: 10400 }
  ];

  let currentLogIdx = 0;
  const timers = [];

  const triggerNextLog = () => {
    if (currentLogIdx < logs.length) {
      const log = logs[currentLogIdx];
      const timer = setTimeout(() => {
        onLog(log.text, log.type);
        currentLogIdx++;
        triggerNextLog();
      }, log.delay - (currentLogIdx > 0 ? logs[currentLogIdx - 1].delay : 0));
      timers.push(timer);
    } else {
      // Completed! Return the seeded reel object
      const newReel = {
        url: reelUrl,
        title,
        caption: `Simulated caption for ${reelUrl}. Automatically extracted from headers.`,
        summary,
        category,
        transcript,
        notes,
        createdAt: Date.now(),
        status: 'completed',
        isFavorite: 0
      };
      
      const timer = setTimeout(() => {
        onComplete(newReel);
      }, 500);
      timers.push(timer);
    }
  };

  triggerNextLog();

  return {
    cancel: () => {
      timers.forEach(clearTimeout);
    }
  };
}
